//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaQuery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public long Id { get; set; }
        public Nullable<int> UserSearchId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string TweetText { get; set; }
        public string Lang { get; set; }
        public string ResultType { get; set; }
        public Nullable<long> UserId { get; set; }
        public string ScreenName { get; set; }
        public Nullable<int> FollowersCount { get; set; }
        public Nullable<int> FriendsCount { get; set; }
        public Nullable<int> FavoritesCount { get; set; }
        public Nullable<int> StatusesCount { get; set; }
        public Nullable<int> RetweetCount { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string JsonTweetElement { get; set; }
        public Nullable<long> TweetId { get; set; }
        public Nullable<double> Score { get; set; }
        public string KeyPhrases { get; set; }
    
        public virtual UserSearch UserSearch { get; set; }
    }
}
