//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaQuery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DEV_DB_LICEntities2 : DbContext
    {
        public DEV_DB_LICEntities2()
            : base("name=DEV_DB_LICEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataSource> DataSources { get; set; }
        public virtual DbSet<SearchResult> SearchResults { get; set; }
        public virtual DbSet<UserSearch> UserSearches { get; set; }
    
        public virtual int usp_ImportTweetsBySearchId(Nullable<int> searchId)
        {
            var searchIdParameter = searchId.HasValue ?
                new ObjectParameter("SearchId", searchId) :
                new ObjectParameter("SearchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ImportTweetsBySearchId", searchIdParameter);
        }
    }
}
