//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaQuery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSearch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSearch()
        {
            this.SearchResults = new HashSet<SearchResult>();
        }
    
        public int Id { get; set; }
        public string QueryText { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DataSourceId { get; set; }
        public string JsonResult { get; set; }
    
        public virtual DataSource DataSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchResult> SearchResults { get; set; }
    }
}
